name: Weekday Crawler2

on:
  schedule:
    - cron: "0 22 * * 0-4"
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  run_crawler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        
      - name: Get workspace path
        run: echo "The workspace path is $GITHUB_WORKSPACE"  
        
      - name: Set up Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: 3.11.4

      - name: Run crawler
        run: python data/get.py
             echo "Spider execution and Excel update completed"
      - name: List files 
        run: | 
          dir -a
