name: Weekday Crawler

on:
  workflow_dispatch:
env:
  TZ: Asia/Shanghai

jobs:
  run_crawler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        
      - name: Get workspace path
        run: echo "The workspace path is $GITHUB_WORKSPACE"  
        
      - name: Set up Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: 3.11.4

      - name: Install dependencies
        run: |
          pip install requests
          pip install openpyxl
          pip install pandas
          pip install chinese-calendar

      - name: Run crawler
        run: python get_market_valume.py
             echo "Spider execution and Excel update completed"
      - name: List files 
        run: | 
          dir -a
      - name: Change file permissions
        run: chmod 777 '市场交易量.xlsx'

      - name: Archive updated Excel file
        uses: actions/upload-artifact@v3.1.3
        with:
          name: updated_excel
          path: 市场交易量.xlsx 
      
      - name: Clean up working directory
        run: rm 市场交易量.xlsx
      
      - name: Add updated file
        run: |
          git add 市场交易量.xlsx
          git commit -m "Update market volume file"

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
           github_token: ${{ secrets.SCRIPY_SECRET }}
